import { cn } from '@/lib/utils';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navigation from '@/components/navigation';
import PatternBackground from '@/components/PatternBackground';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Ruan Engelbrecht | Software Engineer',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(inter.className, 'bg-zinc-900 text-white')}>
        <Navigation />
        <PatternBackground />
        <div>{children}</div>
      </body>
    </html>
  );
}
